/**
 * pdf.ts — turn a block of HTML into a PDF.
 *
 * Called by the web app (web/src/app/api/trips/[id]/pdf/route.ts), which renders
 * the trip document component to static markup and posts it here. Protected by
 * x-internal-key, enforced by the parent plugin in src/index.ts.
 *
 * WHY HEADLESS CHROME AND NOT A PDF LIBRARY
 * The documents are Thai, with Japanese place names in them. Thai stacks tone
 * marks above vowels above consonants and needs real OpenType mark positioning;
 * Japanese needs a CJK font. A JS PDF library can be made to do the first with a
 * vendored font — this was tried, and Noto Sans Thai via @react-pdf did render
 * Thai correctly — but it drew "→" as an apostrophe and every CJK character as
 * tofu, because the font simply has no glyph for them and there is no fallback
 * chain. Chrome has a font fallback chain. Installing two apt packages is a
 * smaller, more honest fix than vendoring a font per script and hoping the set
 * is complete.
 *
 * It also means the PDF is laid out by the same engine as the on-screen page,
 * from the same component — so the file cannot drift from what the user saw.
 *
 * BROWSER LIFETIME
 * One browser is launched lazily and reused. Launching per request costs ~1s
 * and a lot of memory churn; keeping one alive costs a few hundred MB of idle
 * RSS, which is the better trade for a container that already runs sharp and
 * ghostscript. Each request still gets a fresh page, so nothing leaks between
 * documents.
 */
import type { FastifyInstance } from "fastify"
import type { Browser } from "puppeteer-core"

/**
 * Where Chrome lives. The Debian container installs `chromium`; a developer's
 * Mac has Google Chrome. Neither is discovered automatically by puppeteer-core
 * (it ships no browser), so the path is explicit and overridable.
 */
const CHROME_PATHS = [
  process.env.CHROME_PATH,
  "/usr/bin/chromium",
  "/usr/bin/chromium-browser",
  "/usr/bin/google-chrome",
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
].filter((p): p is string => !!p)

let browserPromise: Promise<Browser> | null = null

async function getBrowser(): Promise<Browser> {
  if (browserPromise) {
    try {
      const b = await browserPromise
      if (b.connected) return b
    } catch { /* fall through and relaunch */ }
    // A browser that died (OOM kill, crash) must not be handed out again.
    browserPromise = null
  }

  browserPromise = (async () => {
    const { existsSync } = await import("fs")
    const executablePath = CHROME_PATHS.find(p => existsSync(p))
    if (!executablePath) {
      throw new Error(
        "ไม่พบ Chrome/Chromium สำหรับสร้าง PDF — ติดตั้งแพ็กเกจ chromium ในคอนเทนเนอร์ " +
        "หรือกำหนด CHROME_PATH ให้ชี้ไปที่ไฟล์ปฏิบัติการ",
      )
    }
    const puppeteer = await import("puppeteer-core")
    const { mkdtemp } = await import("fs/promises")
    const { tmpdir } = await import("os")
    const { join } = await import("path")

    // A profile directory of our own.
    //
    // Without this, Chrome uses its DEFAULT profile — and if a Chrome is already
    // running against that profile (every developer machine, and anything else
    // on the host that drives a browser), the new process hands off to the
    // existing one and exits without ever printing a DevTools endpoint.
    // puppeteer then waits for a WebSocket URL that will never arrive and fails
    // with "Timed out after 30000 ms while waiting for the WS endpoint URL to
    // appear in stdout" — which reads like a crash and is really a collision.
    const userDataDir = await mkdtemp(join(tmpdir(), "slippy-pdf-"))

    return puppeteer.launch({
      executablePath,
      headless: true,
      userDataDir,
      // --no-sandbox is required to run as root in a container. The pages this
      // renders are generated by our own server from our own database and never
      // load remote content (see the CSP meta in the HTML the caller sends), so
      // there is no untrusted script for the sandbox to contain.
      args: ["--no-sandbox", "--disable-dev-shm-usage", "--disable-gpu"],
      timeout: 45_000,
    })
  })()

  return browserPromise
}

export async function pdfRoutes(app: FastifyInstance) {
  /**
   * POST /pdf/render
   * Body: { html: string, landscape?: boolean, marginMm?: number }
   * → application/pdf bytes
   */
  app.post<{ Body: { html?: string; landscape?: boolean; marginMm?: number } }>(
    "/pdf/render",
    async (req, reply) => {
      const { html, landscape = false, marginMm = 12 } = req.body ?? {}
      if (!html || typeof html !== "string" || !html.trim()) {
        return reply.code(400).send({ error: "html จำเป็นต้องมี" })
      }
      if (html.length > 6_000_000) {
        return reply.code(413).send({ error: "เอกสารใหญ่เกินไป" })
      }

      const started = Date.now()
      let page
      try {
        const browser = await getBrowser()
        page = await browser.newPage()

        // No network. The HTML arrives fully inlined; a page that cannot reach
        // outward cannot be made to fetch anything by content that ended up in
        // the document, and it removes the slowest failure mode (waiting on a
        // remote asset that will never load).
        await page.setRequestInterception(true)
        page.on("request", r => {
          const url = r.url()
          if (url.startsWith("data:") || url === "about:blank") r.continue()
          else r.abort()
        })

        await page.setContent(html, { waitUntil: "domcontentloaded", timeout: 30_000 })
        // Let webfont-free layout settle; Chrome resolves system fonts
        // synchronously, so this is about CSS layout rather than downloads.
        await page.evaluateHandle("document.fonts.ready")

        const pdf = await page.pdf({
          format: "A4",
          landscape,
          printBackground: true,
          margin: {
            top: `${marginMm}mm`, bottom: `${marginMm}mm`,
            left: `${marginMm}mm`, right: `${marginMm}mm`,
          },
        })

        app.log.info({ bytes: pdf.length, htmlChars: html.length, ms: Date.now() - started }, "pdf rendered")
        return reply
          .header("Content-Type", "application/pdf")
          .header("Content-Length", String(pdf.length))
          .send(Buffer.from(pdf))
      } catch (err) {
        const raw = err instanceof Error ? err.message : "สร้าง PDF ไม่สำเร็จ"
        // Translate the two failures that actually happen into something the
        // person reading them can act on. "Timed out waiting for the WS
        // endpoint" tells you nothing about Chrome not being installed.
        const message =
          raw.includes("WS endpoint") || raw.includes("Failed to launch")
            ? "เปิด Chrome สำหรับสร้าง PDF ไม่ได้ — ตรวจว่าติดตั้ง chromium ในคอนเทนเนอร์แล้ว หรือกำหนด CHROME_PATH"
            : raw.includes("ไม่พบ Chrome") ? raw
            : `สร้าง PDF ไม่สำเร็จ: ${raw}`
        // A browser that failed to start must not be handed out again.
        browserPromise = null
        app.log.error({ raw, ms: Date.now() - started }, "pdf render failed")
        return reply.code(502).send({ error: message })
      } finally {
        // Always close the page, even when rendering threw — an orphaned page
        // holds a renderer process, and a few of those exhaust the container.
        await page?.close().catch(() => {})
      }
    },
  )

  app.addHook("onClose", async () => {
    if (!browserPromise) return
    await browserPromise.then(b => b.close()).catch(() => {})
    browserPromise = null
  })
}
