import React, { useState } from 'react'
import {
  Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text,
  TextInput, TouchableOpacity, View,
} from 'react-native'
import { LinearGradient } from 'expo-linear-gradient'
import { useRouter } from 'expo-router'

const GREEN = '#08783f'
const FOREST = '#064e3b'
const MINT = '#ecfdf5'
const BG = '#f7f8f5'
const BORDER = '#e3e8e2'
const MUTED = '#647067'

type Tab = 'overview' | 'plan' | 'map' | 'budget' | 'more'
type Sheet = 'create' | 'stop' | 'expense' | null

const tabs: Array<{ id: Tab; label: string; icon: string }> = [
  { id: 'overview', label: 'Overview', icon: '◉' },
  { id: 'plan', label: 'Plan', icon: '▣' },
  { id: 'map', label: 'Map', icon: '⌖' },
  { id: 'budget', label: 'Budget', icon: '฿' },
  { id: 'more', label: 'More', icon: '•••' },
]

const stops = [
  { time: '08:30', title: 'Fushimi Inari Taisha', note: 'Explore the iconic torii gates', travel: '18 min · Train', color: '#0f766e' },
  { time: '10:30', title: 'Kiyomizu-dera Temple', note: 'Historic temple with great views', travel: '24 min · Bus', color: '#2563eb' },
  { time: '13:00', title: 'Lunch in Gion', note: 'Try local Kyoto cuisine', travel: '8 min · Walk', color: '#ea580c' },
  { time: '16:00', title: 'Arashiyama Bamboo Grove', note: 'Peaceful walk in nature', travel: '32 min · Train', color: '#65a30d' },
]

function Header({ onCreate }: { onCreate: () => void }) {
  const router = useRouter()
  return <View style={s.header}>
    <TouchableOpacity onPress={() => router.back()} style={s.iconButton}><Text style={s.iconButtonText}>‹</Text></TouchableOpacity>
    <View style={{ flex: 1 }}><Text style={s.headerTitle}>Slippy Journey</Text><Text style={s.headerSub}>Interactive prototype · local demo data</Text></View>
    <TouchableOpacity onPress={onCreate} style={s.newButton}><Text style={s.newButtonText}>＋ New</Text></TouchableOpacity>
  </View>
}

function TripHero() {
  return <LinearGradient colors={['#082f49', '#065f46', '#b45309']} start={{x:0,y:0}} end={{x:1,y:1}} style={s.hero}>
    <View style={s.heroGlow}/><View style={s.heroTop}><View style={s.pill}><Text style={s.pillText}>OFFLINE READY</Text></View><Text style={s.heroMenu}>•••</Text></View>
    <View style={{ flex: 1, justifyContent: 'flex-end' }}><Text style={s.heroTitle}>Japan in Autumn</Text><Text style={s.heroSub}>12–20 Nov 2025 · 9 Days · Japan</Text><View style={s.avatarRow}>{['C','M','T','N'].map((x,i)=><View key={x} style={[s.avatar,{backgroundColor:['#f97316','#db2777','#2563eb','#7c3aed'][i]}]}><Text style={s.avatarText}>{x}</Text></View>)}<View style={s.avatarMore}><Text style={s.avatarMoreText}>+2</Text></View></View></View>
  </LinearGradient>
}

function ProgressCard() {
  return <View style={s.card}><View style={s.rowBetween}><View><Text style={s.eyebrow}>TRIP READINESS</Text><Text style={s.bigValue}>72%</Text></View><View style={s.checkBadge}><Text style={{color:'#fff',fontWeight:'900'}}>✓</Text></View></View><View style={s.track}><View style={[s.fill,{width:'72%'}]}/></View><View style={[s.rowBetween,{marginTop:14}]}><Text style={s.muted}>14 / 19 stops planned</Text><Text style={s.muted}>8 / 12 checklist</Text></View></View>
}

function Overview({ onPlan }: { onPlan: () => void }) {
  return <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><TripHero/><View style={s.quickRow}>{[['＋','Add stop'],['♧','Invite'],['฿','Expense'],['▧','Photo']].map(x=><TouchableOpacity key={x[1]} style={s.quick}><Text style={s.quickIcon}>{x[0]}</Text><Text style={s.quickText}>{x[1]}</Text></TouchableOpacity>)}</View><ProgressCard/><View style={s.sectionHead}><View><Text style={s.eyebrow}>UP NEXT</Text><Text style={s.sectionTitle}>Day 2 · Kyoto</Text></View><TouchableOpacity onPress={onPlan}><Text style={s.link}>View plan</Text></TouchableOpacity></View><View style={s.mapMini}><View style={s.mapRoadA}/><View style={s.mapRoadB}/>{[['1',25,45],['2',49,80],['3',71,128]].map(p=><View key={String(p[0])} style={[s.pin,{left:p[1] as number,top:p[2] as number}]}><Text style={s.pinText}>{p[0]}</Text></View>)}<View style={s.mapSheet}><Text style={s.mapSheetTitle}>Kyoto route</Text><Text style={s.mapSheetSub}>4 stops · 7.8 km · 1h 12m travel</Text></View></View><View style={s.warning}><Text style={{fontSize:20}}>⚠️</Text><View style={{flex:1}}><Text style={s.warningTitle}>Tight connection</Text><Text style={s.warningSub}>Gion → lunch has only 6 minutes buffer</Text></View></View></ScrollView>
}

function Plan({ onAdd }: { onAdd: () => void }) {
  const [done,setDone]=useState<number[]>([])
  return <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{[1,2,3,4,5].map(d=><TouchableOpacity key={d} style={[s.day,d===2&&s.dayActive]}><Text style={[s.daySmall,d===2&&s.dayActiveText]}>DAY {d}</Text><Text style={[s.dayDate,d===2&&s.dayActiveText]}>{10+d} Nov</Text><Text style={[s.dayCity,d===2&&s.dayActiveText]}>{d===1?'Tokyo':d<4?'Kyoto':'Osaka'}</Text></TouchableOpacity>)}</ScrollView><View style={[s.rowBetween,{marginTop:20,marginBottom:12}]}><View><Text style={s.sectionTitle}>Kyoto classics</Text><Text style={s.muted}>4 stops · 08:30–17:30</Text></View><TouchableOpacity onPress={onAdd} style={s.addSmall}><Text style={s.addSmallText}>＋ Add Stop</Text></TouchableOpacity></View><View style={s.timeline}>{stops.map((stop,i)=>{const isDone=done.includes(i); return <View key={stop.title} style={s.stopRow}><Text style={s.stopTime}>{stop.time}</Text><View style={s.lineWrap}>{i<stops.length-1&&<View style={s.line}/>}<TouchableOpacity onPress={()=>setDone(v=>isDone?v.filter(x=>x!==i):[...v,i])} style={[s.dot,{backgroundColor:isDone?'#16a34a':stop.color}]}><Text style={s.dotText}>{isDone?'✓':i+1}</Text></TouchableOpacity></View><View style={[s.stopCard,isDone&&{opacity:.5}]}><View style={s.rowBetween}><View style={{flex:1}}><Text style={[s.stopTitle,isDone&&{textDecorationLine:'line-through'}]}>{stop.title}</Text><Text style={s.stopNote}>{stop.note}</Text></View><View style={[s.thumb,{backgroundColor:stop.color}]}/></View><View style={s.travel}><Text style={s.travelText}>↳ {stop.travel}</Text><Text style={s.travelText}>›</Text></View></View></View>})}</View><TouchableOpacity style={s.ideas}><Text style={s.ideasText}>✨ Ideas inbox · 3 unplanned places</Text><Text style={s.muted}>›</Text></TouchableOpacity></ScrollView>
}

function MapView() {
  return <View style={{flex:1,backgroundColor:'#dfece1'}}><View style={s.fullMap}><View style={s.mapRoadA}/><View style={[s.mapRoadB,{height:520,top:20,left:170,transform:[{rotate:'26deg'}]}]}/><View style={[s.mapRoute,{transform:[{rotate:'19deg'}]}]}/>{[['1',85,130],['2',168,248],['3',235,360],['4',112,470]].map(p=><View key={String(p[0])} style={[s.pin,s.bigPin,{left:p[1] as number,top:p[2] as number}]}><Text style={s.pinText}>{p[0]}</Text></View>)}<View style={s.mapControls}><TouchableOpacity style={s.control}><Text>＋</Text></TouchableOpacity><TouchableOpacity style={s.control}><Text>−</Text></TouchableOpacity><TouchableOpacity style={s.control}><Text>⌖</Text></TouchableOpacity></View><View style={s.routeCard}><View><Text style={s.eyebrow}>DAY 2 ROUTE</Text><Text style={s.sectionTitle}>Kyoto · 4 stops</Text><Text style={s.muted}>7.8 km · estimated 1h 12m</Text></View><TouchableOpacity style={s.navigate}><Text style={s.navigateText}>Navigate</Text></TouchableOpacity></View></View></View>
}

function Budget({ onExpense }: { onExpense: () => void }) {
  const cats: Array<[string, number, string, string]> = [['Accommodation',46,'฿19,620','#7c3aed'],['Transport',27,'฿11,440','#0284c7'],['Food',18,'฿7,680','#16a34a'],['Activities',9,'฿3,940','#ea580c']]
  return <ScrollView contentContainerStyle={s.content}><LinearGradient colors={[FOREST,'#08783f']} style={s.budgetHero}><Text style={s.budgetLabel}>Spent</Text><Text style={s.budgetValue}>฿42,680</Text><View style={s.budgetTrack}><View style={s.budgetFill}/></View><View style={s.rowBetween}><Text style={s.budgetSub}>Budget ฿80,000</Text><Text style={s.budgetSub}>Remaining ฿37,320</Text></View></LinearGradient><View style={s.card}><View style={s.rowBetween}><Text style={s.sectionTitle}>Categories</Text><Text style={s.link}>Details</Text></View>{cats.map(c=><View key={c[0]} style={{marginTop:17}}><View style={s.rowBetween}><Text style={s.category}>{c[0]}</Text><Text style={s.categoryValue}>{c[2]}</Text></View><View style={s.catTrack}><View style={[s.catFill,{width:`${c[1]}%` as any,backgroundColor:c[3]}]}/></View></View>)}</View><View style={s.card}><View style={s.rowBetween}><View><Text style={s.sectionTitle}>Recent expenses</Text><Text style={s.muted}>Original currency + stored rate</Text></View><TouchableOpacity onPress={onExpense} style={s.addSmall}><Text style={s.addSmallText}>＋ Add</Text></TouchableOpacity></View>{[['Hotel Gracery','฿18,400'],['Shinkansen','฿7,920'],['Lunch in Gion','฿1,340']].map((x,i)=><View key={x[0]} style={s.expenseRow}><View style={[s.expenseIcon,{backgroundColor:['#ede9fe','#e0f2fe','#dcfce7'][i]}]}><Text>{['🏨','🚆','🍜'][i]}</Text></View><Text style={s.expenseName}>{x[0]}</Text><Text style={s.expenseValue}>{x[1]}</Text></View>)}</View></ScrollView>
}

function More() {
  const [sub,setSub]=useState<'menu'|'gallery'|'notes'|'together'|'safety'>('menu')
  const [sharing,setSharing]=useState(false)
  if(sub==='gallery') return <ScrollView contentContainerStyle={s.content}><TouchableOpacity onPress={()=>setSub('menu')}><Text style={s.backLink}>‹ More</Text></TouchableOpacity><Text style={s.pageTitle}>Gallery</Text><Text style={s.pageSub}>152 memories · 8 unplaced</Text><View style={s.gallery}>{Array.from({length:9}).map((_,i)=><LinearGradient key={i} colors={[["#bae6fd","#2563eb"],["#fecdd3","#c2410c"],["#bbf7d0","#047857"]][i%3]} style={[s.galleryTile,i===0&&s.galleryTall]}><Text style={s.galleryEmoji}>{['⛩️','🏙️','🎋','🍜','🗻'][i%5]}</Text></LinearGradient>)}</View></ScrollView>
  if(sub==='notes') return <ScrollView contentContainerStyle={s.content}><TouchableOpacity onPress={()=>setSub('menu')}><Text style={s.backLink}>‹ More</Text></TouchableOpacity><Text style={s.pageTitle}>Notes & Checklist</Text><Text style={s.pageSub}>Trip knowledge shared with collaborators</Text>{['Travel tips','Packing list','Hotel check-in','Important contacts'].map((x,i)=><TouchableOpacity key={x} style={s.noteRow}><View style={s.noteIcon}><Text>{i===1?'✓':'▧'}</Text></View><View style={{flex:1}}><Text style={s.noteTitle}>{x}</Text><Text style={s.muted}>{['Useful tips for Japan','8 of 12 completed','Check-in after 3 PM','Emergency numbers'][i]}</Text></View><Text style={s.muted}>›</Text></TouchableOpacity>)}</ScrollView>
  if(sub==='together') return <ScrollView contentContainerStyle={s.content}><TouchableOpacity onPress={()=>setSub('menu')}><Text style={s.backLink}>‹ More</Text></TouchableOpacity><Text style={s.pageTitle}>Travel together</Text><Text style={s.pageSub}>Friends · chat · calls · location</Text><View style={s.card}><Text style={s.sectionTitle}>Trip group · 4 travelers</Text><View style={[s.quickRow,{marginTop:14}]}>{[['LINE','Invite'],['♧','Slippy'],['☎','Call'],['▣','Video']].map(x=><TouchableOpacity key={x[1]} style={s.quick}><Text style={s.quickIcon}>{x[0]}</Text><Text style={s.quickText}>{x[1]}</Text></TouchableOpacity>)}</View></View><View style={s.card}><Text style={s.sectionTitle}>Group chat</Text>{['Mint: ถึง Kyoto Station แล้ว','You: เจอกันที่ Exit 2 นะ'].map((x,i)=><View key={x} style={{alignSelf:i?'flex-end':'flex-start',backgroundColor:i?GREEN:'#edf0ed',padding:11,borderRadius:14,marginTop:9}}><Text style={{fontSize:11,color:i?'#fff':'#17221b'}}>{x}</Text></View>)}</View><View style={[s.card,sharing&&{backgroundColor:MINT,borderColor:'#6ee7b7'}]}><Text style={s.sectionTitle}>⌖ Live location room</Text><Text style={[s.muted,{marginTop:5}]}>Trip members only · auto stop in 60 minutes</Text><TouchableOpacity onPress={()=>setSharing(!sharing)} style={[s.primary,{marginTop:14},sharing&&{backgroundColor:'#b91c1c'}]}><Text style={s.primaryText}>{sharing?'Stop sharing now':'Share for 60 minutes'}</Text></TouchableOpacity><Text style={[s.prototypeNote,{marginTop:10}]}>Visible consent · revocable anytime · no silent tracking</Text></View></ScrollView>
  if(sub==='safety') return <ScrollView contentContainerStyle={s.content}><TouchableOpacity onPress={()=>setSub('menu')}><Text style={s.backLink}>‹ More</Text></TouchableOpacity><Text style={s.pageTitle}>Travel Safety Hub</Text><Text style={s.pageSub}>Emergency help and essential trip records</Text><TouchableOpacity style={[s.card,{backgroundColor:'#fff1f2',borderColor:'#fecdd3'}]}><Text style={{fontSize:30}}>🆘</Text><Text style={[s.sectionTitle,{color:'#9f1239',marginTop:8}]}>Emergency SOS</Text><Text style={s.muted}>Confirm country and emergency service before calling</Text></TouchableOpacity>{[['🏥','Hospitals nearby','2.4 km'],['💊','Medication card','2 medicines · 1 allergy'],['🏨','Hotel & insurance','Booking and policy'],['☎','Embassy & contacts','Available offline']].map(x=><TouchableOpacity key={x[1]} style={s.noteRow}><View style={s.noteIcon}><Text>{x[0]}</Text></View><View style={{flex:1}}><Text style={s.noteTitle}>{x[1]}</Text><Text style={s.muted}>{x[2]}</Text></View><Text style={s.muted}>›</Text></TouchableOpacity>)}<Text style={s.prototypeNote}>Health data is shared only when its owner explicitly chooses it. This does not replace local emergency services.</Text></ScrollView>
  return <ScrollView contentContainerStyle={s.content}><Text style={s.pageTitle}>More</Text><Text style={s.pageSub}>Travel together, safety and trip settings</Text><View style={s.menuGrid}>{[['♧','Travel together','LINE · chat · calls · location',()=>setSub('together')],['♡','Safety hub','SOS · hospital · medication',()=>setSub('safety')],['▧','Gallery & media map','152 photos',()=>setSub('gallery')],['✓','Notes & checklist','8 / 12 done',()=>setSub('notes')],['↓','Offline downloads','Kyoto ready',()=>{}],['⚙','Trip settings','Privacy · currency',()=>{}]].map(x=><TouchableOpacity key={x[1] as string} onPress={x[3] as ()=>void} style={s.menuCard}><View style={s.menuIcon}><Text style={{fontSize:20,color:GREEN}}>{x[0] as string}</Text></View><Text style={s.menuTitle}>{x[1] as string}</Text><Text style={s.muted}>{x[2] as string}</Text></TouchableOpacity>)}</View></ScrollView>
}

function FormField({ label, value }: { label: string; value: string }) { return <View><Text style={s.fieldLabel}>{label}</Text><View style={s.field}><Text style={s.fieldValue}>{value}</Text><Text style={s.muted}>›</Text></View></View> }

function PrototypeSheet({ type, onClose }: { type: Exclude<Sheet,null>; onClose: () => void }) {
  const title={create:'Create New Trip',stop:'Add Stop',expense:'Expense Details'}[type]
  return <Modal visible animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView style={s.modal}><View style={s.modalHeader}><TouchableOpacity onPress={onClose}><Text style={s.cancel}>Cancel</Text></TouchableOpacity><Text style={s.modalTitle}>{title}</Text><View style={{width:52}}/></View><ScrollView contentContainerStyle={s.form}>
    {type==='create'&&<><View style={s.stepRow}>{['Basics','Dates','Travelers','Style'].map((x,i)=><View key={x} style={{alignItems:'center',flex:1}}><View style={[s.step,i===0&&s.stepActive]}><Text style={[s.stepText,i===0&&{color:'#fff'}]}>{i+1}</Text></View><Text style={s.stepLabel}>{x}</Text></View>)}</View><LinearGradient colors={['#0c4a6e','#065f46','#b45309']} style={s.cover}><Text style={s.coverTitle}>Japan in Autumn</Text><Text style={s.coverSub}>Cover preview</Text></LinearGradient><TextInput defaultValue="Japan in Autumn" style={s.input}/><FormField label="Destination" value="🇯🇵  Japan"/><View style={s.formRow}><View style={{flex:1}}><FormField label="Start date" value="12 Nov 2025"/></View><View style={{flex:1}}><FormField label="End date" value="20 Nov 2025"/></View></View><FormField label="Time zone" value="Asia/Tokyo"/><FormField label="Base currency" value="JPY · Japanese Yen"/></>}
    {type==='stop'&&<><TextInput placeholder="Search places or activities" style={s.input}/><View style={s.chips}>{['Attraction','Food','Culture','Nature','Shopping'].map((x,i)=><View key={x} style={[s.chip,i===0&&s.chipActive]}><Text style={[s.chipText,i===0&&{color:GREEN}]}>{x}</Text></View>)}</View>{['Kinkaku-ji Temple','Nishiki Market','Arashiyama Bamboo Grove','Ryoan-ji Temple'].map((x,i)=><TouchableOpacity key={x} style={s.placeRow}><LinearGradient colors={i%2?['#fed7aa','#c2410c']:['#bbf7d0','#047857']} style={s.placeThumb}/><View style={{flex:1}}><Text style={s.placeTitle}>{x}</Text><Text style={s.muted}>Kyoto · 4.{7-i} ★</Text></View><View style={s.plus}><Text style={{color:GREEN}}>＋</Text></View></TouchableOpacity>)}<View style={s.formRow}><View style={{flex:1}}><FormField label="Day" value="Day 2"/></View><View style={{flex:1}}><FormField label="Time" value="15:00"/></View></View></>}
    {type==='expense'&&<><View style={s.chips}>{['Hotel','Transport','Food','Activity'].map((x,i)=><View key={x} style={[s.chip,i===2&&s.chipActive]}><Text style={[s.chipText,i===2&&{color:GREEN}]}>{x}</Text></View>)}</View><Text style={s.fieldLabel}>Amount</Text><View style={s.amountField}><TextInput defaultValue="850" keyboardType="decimal-pad" style={s.amountInput}/><Text style={s.amountCurrency}>THB⌄</Text></View><TextInput defaultValue="Lunch at Asakusa" style={s.input}/><FormField label="Paid by" value="Chain"/><FormField label="Split method" value="Equal · 4 people"/><View style={s.receipt}><Text style={{fontSize:22}}>📷</Text><Text style={s.receiptText}>Attach receipt</Text></View></>}
    <TouchableOpacity onPress={onClose} style={s.primary}><Text style={s.primaryText}>{type==='create'?'Create Trip':type==='stop'?'Add to Itinerary':'Save Expense'}</Text></TouchableOpacity><Text style={s.prototypeNote}>Prototype only — this screen does not write production data.</Text>
  </ScrollView></SafeAreaView></Modal>
}

export default function JourneyPrototypeScreen() {
  const [tab,setTab]=useState<Tab>('overview')
  const [sheet,setSheet]=useState<Sheet>(null)
  return <SafeAreaView style={s.safe}><Header onCreate={()=>setSheet('create')}/><View style={s.body}>{tab==='overview'&&<Overview onPlan={()=>setTab('plan')}/>} {tab==='plan'&&<Plan onAdd={()=>setSheet('stop')}/>} {tab==='map'&&<MapView/>} {tab==='budget'&&<Budget onExpense={()=>setSheet('expense')}/>} {tab==='more'&&<More/>}</View><View style={s.tabBar}>{tabs.map(t=><TouchableOpacity key={t.id} onPress={()=>setTab(t.id)} style={s.tab}><Text style={[s.tabIcon,tab===t.id&&s.tabActive]}>{t.icon}</Text><Text style={[s.tabLabel,tab===t.id&&s.tabActive]}>{t.label}</Text></TouchableOpacity>)}</View>{sheet&&<PrototypeSheet type={sheet} onClose={()=>setSheet(null)}/>}</SafeAreaView>
}

const s=StyleSheet.create({
  safe:{flex:1,backgroundColor:'#fff'},body:{flex:1,backgroundColor:BG},content:{padding:16,paddingBottom:32,gap:14},header:{height:62,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderColor:BORDER,backgroundColor:'#fff'},headerTitle:{fontSize:17,fontWeight:'800',color:FOREST},headerSub:{fontSize:10,color:MUTED,marginTop:1},iconButton:{width:36,height:36,borderRadius:12,borderWidth:1,borderColor:BORDER,alignItems:'center',justifyContent:'center'},iconButtonText:{fontSize:27,color:FOREST,marginTop:-4},newButton:{height:36,paddingHorizontal:12,borderRadius:11,backgroundColor:GREEN,justifyContent:'center'},newButtonText:{fontSize:12,fontWeight:'800',color:'#fff'},
  hero:{height:220,borderRadius:24,padding:18,overflow:'hidden'},heroGlow:{position:'absolute',width:220,height:220,borderRadius:110,backgroundColor:'rgba(255,255,255,.12)',right:-70,top:-80},heroTop:{flexDirection:'row',justifyContent:'space-between'},pill:{backgroundColor:'rgba(255,255,255,.88)',paddingHorizontal:9,paddingVertical:5,borderRadius:99},pillText:{fontSize:8,fontWeight:'900',color:FOREST,letterSpacing:.6},heroMenu:{color:'#fff',fontWeight:'900'},heroTitle:{fontSize:28,fontWeight:'900',color:'#fff'},heroSub:{fontSize:11,color:'rgba(255,255,255,.85)',marginTop:4},avatarRow:{flexDirection:'row',marginTop:14},avatar:{width:29,height:29,borderRadius:15,borderWidth:2,borderColor:'#fff',alignItems:'center',justifyContent:'center',marginRight:-5},avatarText:{fontSize:10,fontWeight:'900',color:'#fff'},avatarMore:{width:29,height:29,borderRadius:15,backgroundColor:'rgba(255,255,255,.9)',alignItems:'center',justifyContent:'center',marginLeft:5},avatarMoreText:{fontSize:9,fontWeight:'800',color:FOREST},
  quickRow:{flexDirection:'row',gap:8},quick:{flex:1,alignItems:'center',paddingVertical:12,borderRadius:16,backgroundColor:'#fff',borderWidth:1,borderColor:BORDER},quickIcon:{fontSize:18,color:GREEN,fontWeight:'700'},quickText:{fontSize:9,color:MUTED,marginTop:4,fontWeight:'700'},card:{backgroundColor:'#fff',borderWidth:1,borderColor:BORDER,borderRadius:20,padding:17},rowBetween:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{fontSize:9,fontWeight:'900',color:MUTED,letterSpacing:1},bigValue:{fontSize:28,fontWeight:'900',color:'#17221b',marginTop:2},checkBadge:{width:34,height:34,borderRadius:17,backgroundColor:'#16a34a',alignItems:'center',justifyContent:'center'},track:{height:7,borderRadius:4,backgroundColor:'#edf0ed',marginTop:13,overflow:'hidden'},fill:{height:'100%',borderRadius:4,backgroundColor:'#16a34a'},muted:{fontSize:10,color:MUTED},sectionHead:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',marginTop:4},sectionTitle:{fontSize:17,fontWeight:'800',color:'#17221b'},link:{fontSize:11,fontWeight:'800',color:GREEN},mapMini:{height:220,borderRadius:20,backgroundColor:'#dfece1',overflow:'hidden'},mapRoadA:{position:'absolute',width:450,height:28,backgroundColor:'rgba(255,255,255,.78)',left:-40,top:86,transform:[{rotate:'18deg'}]},mapRoadB:{position:'absolute',width:24,height:340,backgroundColor:'rgba(255,255,255,.8)',left:190,top:-30,transform:[{rotate:'-28deg'}]},mapSheet:{position:'absolute',left:12,right:12,bottom:12,borderRadius:14,padding:12,backgroundColor:'rgba(255,255,255,.94)'},mapSheetTitle:{fontSize:13,fontWeight:'800',color:'#17221b'},mapSheetSub:{fontSize:10,color:MUTED,marginTop:2},pin:{position:'absolute',width:27,height:27,borderRadius:14,backgroundColor:GREEN,borderWidth:3,borderColor:'#fff',alignItems:'center',justifyContent:'center'},pinText:{fontSize:10,fontWeight:'900',color:'#fff'},warning:{flexDirection:'row',gap:10,padding:14,borderRadius:16,backgroundColor:'#fff7ed',borderWidth:1,borderColor:'#fed7aa'},warningTitle:{fontSize:12,fontWeight:'800',color:'#9a3412'},warningSub:{fontSize:10,color:'#c2410c',marginTop:2},
  day:{width:76,padding:10,borderRadius:15,borderWidth:1,borderColor:BORDER,backgroundColor:'#fff'},dayActive:{backgroundColor:MINT,borderColor:'#6ee7b7'},daySmall:{fontSize:8,fontWeight:'900',color:MUTED},dayDate:{fontSize:13,fontWeight:'800',color:'#17221b',marginTop:3},dayCity:{fontSize:9,color:MUTED,marginTop:2},dayActiveText:{color:GREEN},addSmall:{backgroundColor:MINT,borderRadius:10,paddingHorizontal:11,paddingVertical:8,borderWidth:1,borderColor:'#a7f3d0'},addSmallText:{fontSize:10,fontWeight:'800',color:GREEN},timeline:{backgroundColor:'#fff',borderRadius:20,borderWidth:1,borderColor:BORDER,paddingVertical:8},stopRow:{flexDirection:'row',paddingHorizontal:10,paddingVertical:7},stopTime:{width:45,fontSize:9,fontWeight:'700',color:MUTED,paddingTop:8},lineWrap:{width:28,alignItems:'center'},line:{position:'absolute',top:25,bottom:-22,width:1,backgroundColor:'#cbd5cb'},dot:{width:23,height:23,borderRadius:12,alignItems:'center',justifyContent:'center',zIndex:1},dotText:{fontSize:8,fontWeight:'900',color:'#fff'},stopCard:{flex:1,borderWidth:1,borderColor:BORDER,borderRadius:15,padding:12},stopTitle:{fontSize:12,fontWeight:'800',color:'#17221b'},stopNote:{fontSize:9,color:MUTED,marginTop:3},thumb:{width:42,height:42,borderRadius:9,marginLeft:8},travel:{marginTop:10,paddingTop:9,borderTopWidth:1,borderColor:BORDER,flexDirection:'row',justifyContent:'space-between'},travelText:{fontSize:9,color:MUTED},ideas:{padding:15,borderRadius:16,borderWidth:1,borderStyle:'dashed',borderColor:'#a7f3d0',backgroundColor:'#fff',flexDirection:'row',justifyContent:'space-between'},ideasText:{fontSize:11,fontWeight:'700',color:GREEN},
  fullMap:{flex:1,overflow:'hidden'},mapRoute:{position:'absolute',width:8,height:490,backgroundColor:GREEN,left:175,top:65,borderRadius:5},bigPin:{width:34,height:34,borderRadius:17},mapControls:{position:'absolute',right:14,top:18,gap:8},control:{width:40,height:40,borderRadius:13,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',shadowColor:'#000',shadowOpacity:.08,shadowRadius:8},routeCard:{position:'absolute',left:14,right:14,bottom:18,backgroundColor:'rgba(255,255,255,.96)',borderRadius:20,padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},navigate:{backgroundColor:GREEN,paddingHorizontal:14,paddingVertical:10,borderRadius:11},navigateText:{fontSize:10,fontWeight:'800',color:'#fff'},
  budgetHero:{padding:20,borderRadius:22},budgetLabel:{fontSize:11,color:'rgba(255,255,255,.7)'},budgetValue:{fontSize:34,fontWeight:'900',color:'#fff',marginTop:3},budgetTrack:{height:7,borderRadius:4,backgroundColor:'rgba(255,255,255,.18)',marginTop:18,overflow:'hidden'},budgetFill:{height:'100%',width:'53%',backgroundColor:'#fbbf24'},budgetSub:{fontSize:9,color:'rgba(255,255,255,.8)',marginTop:10},category:{fontSize:11,fontWeight:'700',color:'#27352c'},categoryValue:{fontSize:11,fontWeight:'800',color:'#27352c'},catTrack:{height:5,backgroundColor:'#edf0ed',borderRadius:3,marginTop:7,overflow:'hidden'},catFill:{height:'100%',borderRadius:3},expenseRow:{flexDirection:'row',alignItems:'center',paddingVertical:11,borderBottomWidth:1,borderColor:BORDER},expenseIcon:{width:38,height:38,borderRadius:12,alignItems:'center',justifyContent:'center'},expenseName:{flex:1,fontSize:11,fontWeight:'700',color:'#27352c',marginLeft:10},expenseValue:{fontSize:11,fontWeight:'900',color:'#27352c'},
  pageTitle:{fontSize:24,fontWeight:'900',color:'#17221b'},pageSub:{fontSize:11,color:MUTED,marginTop:-9},backLink:{fontSize:12,fontWeight:'800',color:GREEN},menuGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},menuCard:{width:'48.5%',padding:15,borderRadius:18,borderWidth:1,borderColor:BORDER,backgroundColor:'#fff'},menuIcon:{width:39,height:39,borderRadius:13,backgroundColor:MINT,alignItems:'center',justifyContent:'center'},menuTitle:{fontSize:12,fontWeight:'800',color:'#17221b',marginTop:12,marginBottom:3},aiCard:{padding:15,borderRadius:18,borderWidth:1,borderColor:'#fde68a',backgroundColor:'#fffbeb',flexDirection:'row',gap:11,alignItems:'center'},aiTitle:{fontSize:12,fontWeight:'800',color:'#78350f'},aiSub:{fontSize:9,color:'#a16207',marginTop:2},gallery:{flexDirection:'row',flexWrap:'wrap',gap:6},galleryTile:{width:'31.9%',height:125,borderRadius:13,alignItems:'center',justifyContent:'center'},galleryTall:{height:256},galleryEmoji:{fontSize:34},noteRow:{padding:15,borderRadius:16,borderWidth:1,borderColor:BORDER,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',gap:11},noteIcon:{width:38,height:38,borderRadius:11,backgroundColor:MINT,alignItems:'center',justifyContent:'center'},noteTitle:{fontSize:12,fontWeight:'800',color:'#17221b',marginBottom:3},
  tabBar:{height:68,flexDirection:'row',backgroundColor:'#fff',borderTopWidth:1,borderColor:BORDER,paddingTop:7},tab:{flex:1,alignItems:'center'},tabIcon:{fontSize:16,color:'#98a199',fontWeight:'800'},tabLabel:{fontSize:8,color:'#98a199',fontWeight:'700',marginTop:3},tabActive:{color:GREEN},
  modal:{flex:1,backgroundColor:BG},modalHeader:{height:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,borderBottomWidth:1,borderColor:BORDER,backgroundColor:'#fff'},cancel:{fontSize:12,fontWeight:'700',color:MUTED},modalTitle:{fontSize:15,fontWeight:'900',color:'#17221b'},form:{padding:18,gap:15,paddingBottom:42},stepRow:{flexDirection:'row',marginBottom:3},step:{width:24,height:24,borderRadius:12,backgroundColor:'#e5e7eb',alignItems:'center',justifyContent:'center'},stepActive:{backgroundColor:GREEN},stepText:{fontSize:9,fontWeight:'900',color:MUTED},stepLabel:{fontSize:8,color:MUTED,marginTop:4},cover:{height:150,borderRadius:19,padding:16,justifyContent:'flex-end'},coverTitle:{fontSize:22,fontWeight:'900',color:'#fff'},coverSub:{fontSize:9,color:'rgba(255,255,255,.75)'},input:{height:50,borderRadius:14,borderWidth:1,borderColor:BORDER,backgroundColor:'#fff',paddingHorizontal:14,fontSize:13,color:'#17221b'},fieldLabel:{fontSize:9,fontWeight:'800',color:MUTED,marginBottom:6,textTransform:'uppercase',letterSpacing:.5},field:{height:50,borderRadius:14,borderWidth:1,borderColor:BORDER,backgroundColor:'#fff',paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},fieldValue:{fontSize:12,fontWeight:'600',color:'#17221b'},formRow:{flexDirection:'row',gap:10},chips:{flexDirection:'row',gap:7,flexWrap:'wrap'},chip:{paddingHorizontal:11,paddingVertical:8,borderRadius:99,borderWidth:1,borderColor:BORDER,backgroundColor:'#fff'},chipActive:{borderColor:'#6ee7b7',backgroundColor:MINT},chipText:{fontSize:9,fontWeight:'700',color:MUTED},placeRow:{flexDirection:'row',alignItems:'center',padding:10,borderRadius:15,borderWidth:1,borderColor:BORDER,backgroundColor:'#fff'},placeThumb:{width:50,height:50,borderRadius:11,marginRight:11},placeTitle:{fontSize:12,fontWeight:'800',color:'#17221b',marginBottom:3},plus:{width:30,height:30,borderRadius:15,borderWidth:1,borderColor:'#a7f3d0',alignItems:'center',justifyContent:'center'},amountField:{height:62,borderRadius:15,borderWidth:1,borderColor:BORDER,backgroundColor:'#fff',flexDirection:'row',alignItems:'center'},amountInput:{flex:1,paddingHorizontal:15,fontSize:25,fontWeight:'900',color:'#17221b'},amountCurrency:{fontSize:11,fontWeight:'800',color:MUTED,paddingRight:15},receipt:{height:82,borderRadius:15,borderWidth:1,borderStyle:'dashed',borderColor:'#a7f3d0',backgroundColor:'#fff',alignItems:'center',justifyContent:'center',gap:3},receiptText:{fontSize:10,fontWeight:'700',color:GREEN},primary:{height:52,borderRadius:15,backgroundColor:GREEN,alignItems:'center',justifyContent:'center',marginTop:4},primaryText:{fontSize:13,fontWeight:'900',color:'#fff'},prototypeNote:{fontSize:9,color:MUTED,textAlign:'center'},
})
