-- ─────────────────────────────────────────────────────────────────────────────
-- 019_line_bot_improvements.sql
-- LINE Bot schema improvements:
--   • Add RLS policies to line_connections and line_connection_tokens
--   • Add index for fast token lookup
--   • Add display_name to line_connection_tokens (optional UI display)
--   • Ensure source_meta column exists on documents (for LINE message tracking)
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. Ensure source_meta column exists ──────────────────────────────────────
ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS source_meta jsonb DEFAULT '{}';
-- ── 2. RLS on line_connections ───────────────────────────────────────────────
ALTER TABLE line_connections ENABLE ROW LEVEL SECURITY;
-- Org members can read their org's connections
DROP POLICY IF EXISTS "line_connections_select_member" ON line_connections;
CREATE POLICY "line_connections_select_member"
  ON line_connections FOR SELECT
  USING (
    organization_id IN (
      SELECT organization_id FROM organization_members
      WHERE user_id = auth.uid()
    )
  );
-- Only owners/admins can delete connections
DROP POLICY IF EXISTS "line_connections_delete_owner" ON line_connections;
CREATE POLICY "line_connections_delete_owner"
  ON line_connections FOR DELETE
  USING (
    organization_id IN (
      SELECT organization_id FROM organization_members
      WHERE user_id = auth.uid() AND role IN ('owner','admin')
    )
  );
-- Service role only for insert/update (done via API with service key)

-- ── 3. RLS on line_connection_tokens ────────────────────────────────────────
ALTER TABLE line_connection_tokens ENABLE ROW LEVEL SECURITY;
-- User can see their own tokens
DROP POLICY IF EXISTS "line_tokens_select_own" ON line_connection_tokens;
CREATE POLICY "line_tokens_select_own"
  ON line_connection_tokens FOR SELECT
  USING (user_id = auth.uid());
-- User can insert their own tokens
DROP POLICY IF EXISTS "line_tokens_insert_own" ON line_connection_tokens;
CREATE POLICY "line_tokens_insert_own"
  ON line_connection_tokens FOR INSERT
  WITH CHECK (user_id = auth.uid());
-- ── 4. Indexes ────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_line_tokens_token
  ON line_connection_tokens(token)
  WHERE used_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_line_conn_org
  ON line_connections(organization_id);
CREATE INDEX IF NOT EXISTS idx_line_conn_user
  ON line_connections(line_user_id);
-- ── 5. Helper: clean up expired/used tokens (run periodically) ───────────────
CREATE OR REPLACE FUNCTION cleanup_line_tokens()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM line_connection_tokens
  WHERE
    (expires_at < now() - INTERVAL '1 day')
    OR (used_at IS NOT NULL AND used_at < now() - INTERVAL '7 days');
END;
$$;
COMMENT ON TABLE line_connections IS
  'Stores mapping between LINE user IDs and Slippy organization members.
   One LINE user can connect to one organization at a time (UNIQUE on line_user_id).';
COMMENT ON TABLE line_connection_tokens IS
  'Short-lived tokens (6-char codes) generated by the web app.
   User types /connect CODE in LINE to link their account.
   Tokens expire in 15 minutes and are invalidated after use.';
